<?php

namespace App\Jobs;

use App\Events\Tenant\TenantIdentified;
use App\Models\Organization;
use Illuminate\Bus\Queueable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Spatie\MediaLibrary\Jobs\PerformConversions;
use Spatie\MediaLibrary\Conversion\ConversionCollection;
use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\FileManipulator;

class PerformMediaConversions extends PerformConversions implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public function __construct(ConversionCollection $conversions, Media $media)
    {
        parent::__construct($conversions, $media);

    }

    public function handle(): bool
    {
        event(new TenantIdentified(Organization::find(1)));
        return parent::handle(); // TODO: Change the autogenerated stub
    }
}
